#!/bin/bash

# Render 快速部署脚本
# 使用说明：将此脚本保存为 deploy-to-render.sh，然后在 Render 控制台执行

echo "=== IATF CARA 后端部署到 Render ==="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 访问 https://render.com 并登录"
echo "2. 点击 'New Web Service'"
echo "3. 连接 GitHub 仓库: jasonbai123/iatf-cara-pro-1.0"
echo "4. 配置如下："
echo ""
echo "   - Name: iatf-cara-backend"
echo "   - Runtime: Node.js"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo ""
echo "5. 添加环境变量："
echo "   - JWT_SECRET: (请使用以下随机密钥)"
echo ""
# 生成随机密钥
SECRET=$(openssl rand -hex 32)
echo "   $SECRET"
echo ""
echo "   复制上面的密钥，粘贴到 Render 的环境变量中"
echo ""
echo "6. 点击 'Create Web Service' 开始部署"
echo ""
echo "7. 部署完成后，复制 Render 提供的 URL"
echo "   格式类似: https://iatf-cara-backend.onrender.com"
echo ""
echo "8. 更新前端配置："
echo "   修改 .env.local 文件中的 VITE_API_BASE_URL 为您的 Render URL"
echo ""
echo "9. 重新构建并推送前端："
echo "   npm run build"
echo "   git add ."
echo "   git commit -m '更新API配置'"
echo "   git push"
echo ""
echo "=== 部署完成 ==="
